const BASE = 'https://storage.googleapis.com/msgsndr/sxFrugNVp2enL9pfGarC/media';

export type FeedCardType = 'upcoming' | 'recap';
export type MediaType = 'image' | 'video';

export interface FeedEvent {
  id: string;
  type: FeedCardType;
  username: string;
  avatarUrl: string;
  mediaUrl: string;
  mediaType?: MediaType;
  eventTitle: string;
  caption: string;
  timeLabel: string;
  neighborhood?: string;
  date?: string;
  time?: string;
  attending?: number;
  capacity?: number;
  spotsLeft?: number;
  price?: string | null;
  host?: {
    name: string;
    avatarUrl: string;
    memberSince: string;
  };
  description?: string;
  address?: string;
  category?: string;
  emoji?: string;
  hostUserId?: string;
}

// All Bold concept assets
export const ASSETS = {
  // Event media - images
  wineNightImg: `${BASE}/6923e595a470b3044fe0ba57.png`,
  yogaImg: `${BASE}/6923e595460a61be06c59a4d.png`,
  paintingImg: `${BASE}/6923e8dfc7f3f5c74dd4df4d.png`,
  boardGamesImg: `${BASE}/6923e8df460a61b463c5f3dd.png`,
  coffeeImg: `${BASE}/6923e8e1a470b3e342e11147.png`,
  hikeImg: `${BASE}/6923e7602e932b0c9c969020.png`,
  campfireImg: `${BASE}/6923e8d92e932b324196bbdd.png`,
  bikingImg: `${BASE}/6923e8dfc7f3f54405d4df4e.png`,
  cookingImg: `${BASE}/6923e8d92e932bf72196bbde.png`,
  chessImg: `${BASE}/6923e8d9c7f3f572b8d4ded3.png`,
  // Newer Bold assets
  eventImg11: `${BASE}/6937bec2169a42e871da8522.png`,
  eventImg12: `${BASE}/6937bf42e03e9da8a46843a8.png`,
  eventImg13: `${BASE}/6937bfb650387f53907605d3.png`,
  eventImg14: `${BASE}/6937c04d578cc73a00a51ff5.png`,
  eventImg15: `${BASE}/6948fb958dda72c1542bf2cf.png`,
  eventImg16: `${BASE}/694908b2106fdcb1447a0cc7.png`,
  eventImg17: `${BASE}/694908b2106fdcb1447a0cc8.png`,
  // Event media - videos
  wineNightVideo: `${BASE}/6923ee65a470b35c85e1a327.mp4`,
  video2: `${BASE}/6923ec89a470b3f417e175de.mp4`,
  video3: `${BASE}/6923ec8c2e932b1e229723e8.mp4`,
  video4: `${BASE}/6923ee6c460a61190fc688c2.mp4`,
  // Avatars
  avatar1: `${BASE}/6923e760460a6155f2c5c982.png`,
  avatar2: `${BASE}/6923e760460a61e135c5c97f.png`,
  avatar3: `${BASE}/6923e760c7f3f5cf03d4abbf.png`,
  avatar4: `${BASE}/6923de2fa470b36bdfdfd088.png`,
  avatar5: `${BASE}/6923de3c460a615f52c4ae6c.png`,
  avatar6: `${BASE}/6923e760460a61362bc5c980.png`,
  avatar7: `${BASE}/6923e760c7f3f55319d4abbe.png`,
  avatar8: `${BASE}/6923de3c2e932bd12c957f39.png`,
  avatar9: `${BASE}/6924236c2a792758373a8c45.png`,
  avatar10: `${BASE}/6923e760a470b307d3e0e684.png`,
  avatar11: `${BASE}/6923e760a470b33dabe0e682.png`,
  avatar12: `${BASE}/6923e760c7f3f54521d4abc0.png`,
  // Map thumbnail
  mapThumb: `${BASE}/692bd89682f4c548c5143502.png`,
};

export const MOCK_EVENTS: FeedEvent[] = [
  {
    id: '1',
    type: 'upcoming',
    username: '@MingleSpark',
    avatarUrl: ASSETS.avatar1,
    mediaUrl: ASSETS.wineNightVideo,
    mediaType: 'video',
    eventTitle: 'Wine Night',
    caption: 'Nothing beats a Friday wine night ✨ #newfriends',
    timeLabel: 'Tonight at 7 PM',
    neighborhood: 'Downtown',
    date: 'Friday, May 16',
    time: '7:00 PM',
    attending: 4,
    capacity: 6,
    spotsLeft: 2,
    price: 'Free',
    category: 'Social',
    emoji: '🍷',
    description:
      "Join us for a relaxed evening of wine, good vibes, and great conversation. We'll taste a curated selection of reds and whites, learn a few fun wine facts, and enjoy a cozy atmosphere perfect for meeting new people or bringing friends.",
    address: '123 King St W, Downtown',
    host: { name: '@MingleSpark', avatarUrl: ASSETS.avatar1, memberSince: '2024' },
  },
  {
    id: '2',
    type: 'recap',
    username: '@SoulSync',
    avatarUrl: ASSETS.avatar2,
    mediaUrl: ASSETS.video2,
    mediaType: 'video',
    eventTitle: 'Morning Yoga Flow',
    caption: 'Starting the week calm, resetting the mind #selfcare',
    timeLabel: '1d ago',
    category: 'Wellness',
    emoji: '🧘',
    description: 'A gentle morning yoga session to reset and recharge.',
    host: { name: '@SoulSync', avatarUrl: ASSETS.avatar2, memberSince: '2023' },
  },
  {
    id: '3',
    type: 'upcoming',
    username: '@HappyHabit',
    avatarUrl: ASSETS.avatar3,
    mediaUrl: ASSETS.paintingImg,
    mediaType: 'image',
    eventTitle: 'Brush & Chill',
    caption: 'Brush & Chill this Saturday! Spots going fast.',
    timeLabel: 'This Weekend',
    neighborhood: 'Arts District',
    date: 'Saturday, May 17',
    time: '3:00 PM',
    attending: 5,
    capacity: 6,
    spotsLeft: 1,
    price: 'Free',
    category: 'Arts',
    emoji: '🎨',
    description:
      'A chill painting session where you bring your creativity and we provide the supplies. No experience needed — just good vibes and a willingness to get your hands colorful.',
    address: '456 Queen St E, Arts District',
    host: { name: '@HappyHabit', avatarUrl: ASSETS.avatar3, memberSince: '2024' },
  },
  {
    id: '4',
    type: 'recap',
    username: '@BoardGameBoss',
    avatarUrl: ASSETS.avatar4,
    mediaUrl: ASSETS.boardGamesImg,
    mediaType: 'image',
    eventTitle: 'Board Game Jam',
    caption: "Didn't win but laughed until my sides hurt. Best night in weeks.",
    timeLabel: '2d ago',
    category: 'Games',
    emoji: '🎲',
    description: 'Catan, Carcassonne, and Codenames — all in one night.',
    host: { name: '@BoardGameBoss', avatarUrl: ASSETS.avatar4, memberSince: '2023' },
  },
  {
    id: '5',
    type: 'upcoming',
    username: '@LaughingLatte',
    avatarUrl: ASSETS.avatar5,
    mediaUrl: ASSETS.coffeeImg,
    mediaType: 'image',
    eventTitle: 'Coffee & Connections',
    caption: 'Grab a coffee and meet some cool people in the neighborhood.',
    timeLabel: 'This Weekend',
    neighborhood: 'Midtown',
    date: 'Sunday, May 18',
    time: '10:00 AM',
    attending: 3,
    capacity: 6,
    spotsLeft: 3,
    price: 'Free',
    category: 'Social',
    emoji: '☕',
    description:
      'Come grab a coffee and meet some cool people in the neighborhood. No agenda, just good conversation and great coffee.',
    address: '789 Yonge St, Midtown',
    host: { name: '@LaughingLatte', avatarUrl: ASSETS.avatar5, memberSince: '2024' },
  },
  {
    id: '6',
    type: 'upcoming',
    username: '@LaughingLatte',
    avatarUrl: ASSETS.avatar5,
    mediaUrl: ASSETS.video3,
    mediaType: 'video',
    eventTitle: "Chef's Table Secrets",
    caption: "Only 12 seats — a private chef experience you won't forget.",
    timeLabel: 'Next Week',
    neighborhood: 'Little Italy',
    date: 'Wednesday, May 21',
    time: '6:30 PM',
    attending: 10,
    capacity: 12,
    spotsLeft: 2,
    price: '$25',
    category: 'Food & Drink',
    emoji: '🍝',
    description:
      "A private dinner experience where a local chef walks you through the secrets behind three iconic Italian dishes. You'll cook, learn, and eat — all in an intimate setting.",
    address: '101 College St, Little Italy',
    host: { name: '@LaughingLatte', avatarUrl: ASSETS.avatar5, memberSince: '2024' },
  },
  {
    id: '7',
    type: 'recap',
    username: '@UrbanExplorer',
    avatarUrl: ASSETS.avatar6,
    mediaUrl: ASSETS.hikeImg,
    mediaType: 'image',
    eventTitle: 'Sunday Hike',
    caption: 'Fresh air, new trails, good company. The perfect Sunday reset.',
    timeLabel: '3d ago',
    category: 'Outdoors',
    emoji: '🏞️',
    description: 'A relaxed Sunday morning hike through the ravine trails.',
    host: { name: '@UrbanExplorer', avatarUrl: ASSETS.avatar6, memberSince: '2023' },
  },
  {
    id: '8',
    type: 'upcoming',
    username: '@FunWithJamie',
    avatarUrl: ASSETS.avatar9,
    mediaUrl: ASSETS.paintingImg,
    mediaType: 'image',
    eventTitle: 'Bowling Crew Night',
    caption: 'Laid-back bowling night — come as you are, leave with new friends.',
    timeLabel: 'Thursday 8 PM',
    neighborhood: 'Westside',
    date: 'Thursday, May 22',
    time: '8:00 PM',
    attending: 4,
    capacity: 6,
    spotsLeft: 2,
    price: 'Free',
    category: 'Games',
    emoji: '🎳',
    description:
      "Easy going bowling night — doesn't matter if you're good or not. Just show up, have fun, and meet some cool people.",
    address: '234 Bloor St W, Westside',
    host: { name: '@FunWithJamie', avatarUrl: ASSETS.avatar9, memberSince: '2024' },
  },
  {
    id: '9',
    type: 'recap',
    username: '@BoldBeat',
    avatarUrl: ASSETS.avatar7,
    mediaUrl: ASSETS.campfireImg,
    mediaType: 'image',
    eventTitle: 'Stories by the Fire',
    caption: 'Campfire stories, warm vibes, and easy company. The perfect night.',
    timeLabel: '3d ago',
    category: 'Social',
    emoji: '🔥',
    description: "A cozy evening around the fire with stories and s'mores.",
    host: { name: '@BoldBeat', avatarUrl: ASSETS.avatar7, memberSince: '2023' },
  },
  {
    id: '10',
    type: 'upcoming',
    username: '@AdventureLaura',
    avatarUrl: ASSETS.avatar8,
    mediaUrl: ASSETS.bikingImg,
    mediaType: 'image',
    eventTitle: 'Waterfront Bike Ride',
    caption: 'Easy ride along the waterfront. Great views, great people.',
    timeLabel: 'Next Week',
    neighborhood: 'Waterfront',
    date: 'Saturday, May 24',
    time: '9:00 AM',
    attending: 2,
    capacity: 6,
    spotsLeft: 4,
    price: 'Free',
    category: 'Outdoors',
    emoji: '🚴',
    description:
      'A casual bike ride along the waterfront trail. Easy pace, great views, and good company. Bring your own bike!',
    address: 'Waterfront Trail, Queens Quay',
    host: { name: '@AdventureLaura', avatarUrl: ASSETS.avatar8, memberSince: '2024' },
  },
  {
    id: '11',
    type: 'upcoming',
    username: '@ChessClub',
    avatarUrl: ASSETS.avatar10,
    mediaUrl: ASSETS.chessImg,
    mediaType: 'image',
    eventTitle: 'Chess & Chill',
    caption: 'All levels welcome — just bring your brain and good vibes.',
    timeLabel: 'Tomorrow 6 PM',
    neighborhood: 'Annex',
    date: 'Saturday, May 17',
    time: '6:00 PM',
    attending: 3,
    capacity: 8,
    spotsLeft: 5,
    price: 'Free',
    category: 'Games',
    emoji: '♟️',
    description:
      "Whether you're a grandmaster or learning the basics, this is a judgment-free zone for playing chess and meeting like-minded people.",
    address: '350 Bloor St W, The Annex',
    host: { name: '@ChessClub', avatarUrl: ASSETS.avatar10, memberSince: '2024' },
  },
  {
    id: '12',
    type: 'recap',
    username: '@KitchenVibes',
    avatarUrl: ASSETS.avatar11,
    mediaUrl: ASSETS.cookingImg,
    mediaType: 'image',
    eventTitle: 'Dumpling Night',
    caption: 'Folded 300 dumplings and made 12 new friends. Worth it every time.',
    timeLabel: '5d ago',
    category: 'Food & Drink',
    emoji: '🥟',
    description: 'A hands-on dumpling making class with great food at the end.',
    host: { name: '@KitchenVibes', avatarUrl: ASSETS.avatar11, memberSince: '2023' },
  },
  {
    id: '13',
    type: 'upcoming',
    username: '@GlowRun',
    avatarUrl: ASSETS.avatar12,
    mediaUrl: ASSETS.video4,
    mediaType: 'video',
    eventTitle: 'Glow Run 5K',
    caption: '5K under the stars — neon optional, fun mandatory.',
    timeLabel: 'Saturday 9 PM',
    neighborhood: 'Harbourfront',
    date: 'Saturday, May 17',
    time: '9:00 PM',
    attending: 18,
    capacity: 25,
    spotsLeft: 7,
    price: '$10',
    category: 'Outdoors',
    emoji: '🌙',
    description:
      'A 5K night run along the waterfront. Wear your brightest neon and glow gear. Finish line celebration included!',
    address: 'Harbourfront Centre, Queens Quay W',
    host: { name: '@GlowRun', avatarUrl: ASSETS.avatar12, memberSince: '2024' },
  },
  {
    id: '14',
    type: 'upcoming',
    username: '@SoundBath',
    avatarUrl: ASSETS.avatar2,
    mediaUrl: ASSETS.eventImg11,
    mediaType: 'image',
    eventTitle: 'Crystal Sound Bath',
    caption: 'Reset your nervous system with crystal bowls and deep vibrations.',
    timeLabel: 'Tonight at 8 PM',
    neighborhood: 'Kensington',
    date: 'Friday, May 16',
    time: '8:00 PM',
    attending: 6,
    capacity: 12,
    spotsLeft: 6,
    price: '$15',
    category: 'Wellness',
    emoji: '🔮',
    description:
      'A 60-minute guided sound bath using crystal singing bowls and percussion. Perfect for stress relief and deep relaxation.',
    address: '45 Kensington Ave, Kensington Market',
    host: { name: '@SoundBath', avatarUrl: ASSETS.avatar2, memberSince: '2023' },
  },
  {
    id: '15',
    type: 'recap',
    username: '@RooftopCrew',
    avatarUrl: ASSETS.avatar6,
    mediaUrl: ASSETS.eventImg12,
    mediaType: 'image',
    eventTitle: 'Rooftop Sunset Sesh',
    caption: 'The best views in the city. Same time next month? 🌅',
    timeLabel: '1d ago',
    category: 'Social',
    emoji: '🌅',
    description: 'Golden hour on the rooftop with good company and better views.',
    host: { name: '@RooftopCrew', avatarUrl: ASSETS.avatar6, memberSince: '2024' },
  },
  {
    id: '16',
    type: 'upcoming',
    username: '@JazzNight',
    avatarUrl: ASSETS.avatar7,
    mediaUrl: ASSETS.eventImg13,
    mediaType: 'image',
    eventTitle: 'Jazz & Wine Evening',
    caption: 'Live jazz + curated wines. An evening to remember.',
    timeLabel: 'Next Week',
    neighborhood: 'Queen West',
    date: 'Friday, May 23',
    time: '7:30 PM',
    attending: 8,
    capacity: 15,
    spotsLeft: 7,
    price: '$20',
    category: 'Arts',
    emoji: '🎷',
    description:
      'An intimate jazz evening with a live trio, curated wine pairings, and a crowd that appreciates good music. No experience needed — just an open heart.',
    address: '600 Queen St W, Queen West',
    host: { name: '@JazzNight', avatarUrl: ASSETS.avatar7, memberSince: '2023' },
  },
  {
    id: '17',
    type: 'upcoming',
    username: '@PickleballTO',
    avatarUrl: ASSETS.avatar9,
    mediaUrl: ASSETS.eventImg14,
    mediaType: 'image',
    eventTitle: 'Pickleball Social',
    caption: "The sport everyone's obsessed with right now.",
    timeLabel: 'Tomorrow 10 AM',
    neighborhood: 'East End',
    date: 'Sunday, May 18',
    time: '10:00 AM',
    attending: 6,
    capacity: 8,
    spotsLeft: 2,
    price: 'Free',
    category: 'Outdoors',
    emoji: '🏓',
    description:
      "Beginner-friendly pickleball session at Greenwood Park. Paddles provided. Whether you've played before or it's your first time, come out and have a blast.",
    address: 'Greenwood Park, East End',
    host: { name: '@PickleballTO', avatarUrl: ASSETS.avatar9, memberSince: '2024' },
  },
  {
    id: '18',
    type: 'recap',
    username: '@FilmClub',
    avatarUrl: ASSETS.avatar10,
    mediaUrl: ASSETS.eventImg15,
    mediaType: 'image',
    eventTitle: 'Indie Film Night',
    caption: 'We watched, we talked, we disagreed beautifully. See you next month.',
    timeLabel: '4d ago',
    category: 'Arts',
    emoji: '🎬',
    description: 'A monthly indie film screening followed by a group discussion.',
    host: { name: '@FilmClub', avatarUrl: ASSETS.avatar10, memberSince: '2023' },
  },
  {
    id: '19',
    type: 'upcoming',
    username: '@BrunchSquad',
    avatarUrl: ASSETS.avatar11,
    mediaUrl: ASSETS.eventImg16,
    mediaType: 'image',
    eventTitle: 'Sunday Brunch Club',
    caption: 'Mimosas, eggs benny, and zero judgment on your weekend plans.',
    timeLabel: 'This Weekend',
    neighborhood: 'Leslieville',
    date: 'Sunday, May 18',
    time: '11:00 AM',
    attending: 5,
    capacity: 8,
    spotsLeft: 3,
    price: 'Free',
    category: 'Food & Drink',
    emoji: '🥞',
    description:
      'A casual Sunday brunch to kickstart the week right. Good food, better people, zero agenda.',
    address: 'Smith St, Leslieville',
    host: { name: '@BrunchSquad', avatarUrl: ASSETS.avatar11, memberSince: '2024' },
  },
  {
    id: '20',
    type: 'recap',
    username: '@NightMarket',
    avatarUrl: ASSETS.avatar12,
    mediaUrl: ASSETS.eventImg17,
    mediaType: 'image',
    eventTitle: 'Night Market Crawl',
    caption: 'Ate our way through 6 stalls and zero regrets. Part 2 incoming!',
    timeLabel: '6d ago',
    category: 'Food & Drink',
    emoji: '🏮',
    description: 'A group crawl through the best night market stalls in the city.',
    host: { name: '@NightMarket', avatarUrl: ASSETS.avatar12, memberSince: '2023' },
  },
];

export const MAP_THUMBNAIL = ASSETS.mapThumb;

// Convenience alias used by some screens
export const mockEvents = MOCK_EVENTS;
